In [1]:
import pandas as pd
import scipy.stats as stats
import matplotlib.pyplot as plt

In [2]:
# df = pd.read_csv(r"D:\Fall 00\data mining\covid_project\SARS-CoV-2-Dataset\SARS-CoV-2.csv")

In [3]:
# len(df)

In [4]:
#1 Preprocessing

In [5]:
# # people_fully_vaccinated & total_vaccinations NA to 0 & make it logical

# old_location = ''
# max_people_fully_vaccinated = 0 
# max_total_vaccinations = 0

# for i in range(len(df)):
#     location = df.loc[i, "location"]
#     total_vaccinations = df.loc[i, "total_vaccinations"]
#     people_fully_vaccinated = df.loc[i, "people_fully_vaccinated"]  
    
#     if location != old_location:
#         max_people_fully_vaccinated = 0 
#         max_total_vaccinations = 0
#         old_location = location
    
#     if pd.isnull(people_fully_vaccinated):
#         df.loc[i, "people_fully_vaccinated"]  = max_people_fully_vaccinated
#     elif people_fully_vaccinated > max_people_fully_vaccinated:
#         max_people_fully_vaccinated = people_fully_vaccinated
        
        
#     if pd.isnull(total_vaccinations):
#         df.loc[i, "total_vaccinations"] = max_total_vaccinations
#     elif total_vaccinations > max_total_vaccinations:
#         max_total_vaccinations = total_vaccinations

In [6]:
# df.to_csv('SARS-CoV-2-updated.csv', index=False)

In [7]:
df = pd.read_csv("SARS-CoV-2-updated.csv")

In [8]:
# NA to 0

df['people_vaccinated'].fillna(0, inplace=True)
df['new_cases'].fillna(0, inplace=True)
df['new_deaths'].fillna(0, inplace=True)
df['total_vaccinations'].fillna(0, inplace=True)
df.fillna(0, inplace=True)

In [9]:
# Remove NC & INT

print(len(df))

idx_international = df.index[df['location'] == 'International'].tolist()
df.drop(idx_international, inplace=True)

idx_northern_cyprus = df.index[df['location'] == 'Northern Cyprus'].tolist()
df.drop(idx_northern_cyprus, inplace=True)

print(len(df))

136993
136013

In [10]:
# 2

In [11]:
# 2.1 COUNTRY

In [12]:
df['date'] = pd.to_datetime(df['date'])

In [13]:
df_2 = df.copy()
df_2

,iso_code,continent,location,date,total_cases,total_deaths,total_vaccinations,people_vaccinated,people_fully_vaccinated,new_cases,new_deaths,population
0,AFG,Asia,Afghanistan,2020-02-24,5.0,0.0,0.0,0.0,0.0,5.0,0.0,39835428.0
1,AFG,Asia,Afghanistan,2020-02-25,5.0,0.0,0.0,0.0,0.0,0.0,0.0,39835428.0
2,AFG,Asia,Afghanistan,2020-02-26,5.0,0.0,0.0,0.0,0.0,0.0,0.0,39835428.0
3,AFG,Asia,Afghanistan,2020-02-27,5.0,0.0,0.0,0.0,0.0,0.0,0.0,39835428.0
4,AFG,Asia,Afghanistan,2020-02-28,5.0,0.0,0.0,0.0,0.0,0.0,0.0,39835428.0
...,...,...,...,...,...,...,...,...,...,...,...,...
136988,ZWE,Africa,Zimbabwe,2021-11-26,133836.0,4704.0,6544331.0,3757352.0,2786979.0,62.0,0.0,15092171.0
136989,ZWE,Africa,Zimbabwe,2021-11-27,133836.0,4704.0,6560442.0,3765392.0,2795050.0,0.0,0.0,15092171.0
136990,ZWE,Africa,Zimbabwe,2021-11-28,133951.0,4705.0,6568694.0,3770886.0,2797808.0,115.0,1.0,15092171.0
136991,ZWE,Africa,Zimbabwe,2021-11-29,134226.0,4706.0,6586503.0,3782038.0,2804465.0,275.0,1.0,15092171.0
136992,ZWE,Africa,Zimbabwe,2021-11-30,134625.0,4707.0,6611942.0,3795401.0,2816541.0,399.0,1.0,15092171.0

In [14]:
df_2.drop(columns = ['iso_code', 'continent', 'location'], inplace=True)

In [15]:
train_dataset_country = df_2[df_2['date'] <= '2021-10-31']

In [16]:
test_dataset_country = df_2[df_2['date'] <= '2021-11-30']
test_dataset_country = test_dataset_country[test_dataset_country['date'] >= '2021-11-01']

In [17]:
def train(model, t):
    y_train = train_dataset_country[t]
    X_train = train_dataset_country.drop(columns = [t, 'date'])
    model.fit(X_train, y_train)
    return model

In [18]:
def test(model, t):
    X_test = test_dataset_country.drop(columns = [t, 'date'])
    y_pred = model.predict(X_test)
    y_test = test_dataset_country[t]
    return y_pred, y_test

In [19]:
from matplotlib.pyplot import figure
def plot_graph(d, y_pred_lst, y_hat_lst, target, model_name):
#     print('length y_pred_lst=', len(y_pred_lst))
#     print('length y_hat_lst=', len(y_hat_lst))
    figure(figsize=(12, 8), dpi=200)
    x_label = df[df['date'] == base_train_date + datetime.timedelta(days=d)]['location'].values
    t = 40
    plt.plot(x_label[t:t+20], y_pred_lst[t:t+20], color='r', label='Predictions')
    plt.plot(x_label[t:t+20], y_hat_lst[t:t+20], color='g', label='Ground Truth')

    plt.xticks(rotation = 90) # Rotates X-Axis Ticks by 90-degrees

    plt.xlabel("Countries")
    plt.ylabel(target)
    plt.title("Predicting " + target + " " + str(d) + " days later than base date using " + model_name)
    
    plt.legend()
    import os
    dir_name = "figures/" + target
    if not os.path.exists(dir_name):
        os.mkdir(dir_name)
    plt.savefig(dir_name + "/" + model_name + "_" + target + "_" + str(d) + "days_after" + "_plot.jpg")
    plt.close()

In [20]:
import datetime
base_train_date = datetime.datetime(2021,10, 31)

def predict_days(model, t, model_name):
    days = [7, 14, 21, 28, 30]
    for d in days:
#         print('day=', d)
        y_pred_lst = []
        y_hat_lst = []
        X = df_2[df_2['date'] == base_train_date + datetime.timedelta(days=d)]
        for index, row in X.iterrows():
            y_hat_lst.append(row[t])
            x_t = row.drop([t, 'date'])
            y_pred = model.predict(x_t.values.reshape(1, -1))
            y_pred_lst.append(y_pred)
        plot_graph(d, y_pred_lst, y_hat_lst, t, model_name)

In [21]:
from sklearn.metrics import mean_squared_error
from sklearn.metrics import r2_score
from sklearn.metrics import mean_absolute_error

metrics_data = []
def metrics(y_test, y_pred, model_name, t):
    mse = mean_squared_error(y_test, y_pred)
    rmse = mse ** (0.5)
    r2 = r2_score(y_test, y_pred)
    mae = mean_absolute_error(y_test, y_pred)
    
    mrae = 0
    for i in range(len(y_test.values)):
        rae = (abs((y_pred[i] - y_test.values[i]) / (y_test.values[i] + 0.00000001))) * 100
        mrae += rae
    
    mrae /= len(y_test.values)
    
    rrse = 0
    for i in range(len(y_test.values)):
        rse = (((y_pred[i] - y_test.values[i]) / (y_test.values[i] + 0.00000001)) ** 2) * 100
        rrse += rse
    
    rrse /= len(y_test.values)
    
    metrics_data.append([model_name, t, mse, rmse, r2, mae, mrae, rrse])

In [22]:
from sklearn.ensemble import RandomForestRegressor
from sklearn.naive_bayes import GaussianNB
from sklearn.tree import DecisionTreeRegressor

gnb = GaussianNB()
rfr = RandomForestRegressor()
dtr = DecisionTreeRegressor()

In [23]:
target = ['new_cases', 'new_deaths', 'total_cases', 'total_deaths']
models = [rfr, dtr, gnb]
for model in models:
    for t in target:
        model = train(model, t)
        y_pred, y_test = test(model, t)
        
        model_name = type(model).__name__
        metrics(y_test, y_pred, model_name, t)

        predict_days(model, t, model_name)
        print(model_name, t)

RandomForestRegressor new_cases
RandomForestRegressor new_deaths
RandomForestRegressor total_cases
RandomForestRegressor total_deaths
DecisionTreeRegressor new_cases
DecisionTreeRegressor new_deaths
DecisionTreeRegressor total_cases
DecisionTreeRegressor total_deaths

In [24]:
metrics_data_df = pd.DataFrame(data=metrics_data, columns=['model_name', 'target', 'MSE', 'RMSE', 'R2', 'MAE', 'MRAE', 'RRSE'])
metrics_data_df.to_csv('metrics_data_df.csv', index=False)

In [25]:
metrics_data_df

,model_name,target,MSE,RMSE,R2,MAE,MRAE,RRSE
0,RandomForestRegressor,new_cases,2.580445e+08,1.606376e+04,0.901774,3575.323008,1.932702e+11,2.875374e+22
1,RandomForestRegressor,new_deaths,6.963823e+04,2.638906e+02,0.835820,45.515459,5.432759e+09,1.145119e+19
2,RandomForestRegressor,total_cases,5.933002e+12,2.435775e+06,0.987495,460229.333864,2.297614e+10,1.461386e+21
3,RandomForestRegressor,total_deaths,7.955940e+09,8.919607e+04,0.957563,11871.504027,2.728473e+01,8.235843e+01
4,DecisionTreeRegressor,new_cases,2.550780e+08,1.597116e+04,0.902904,3542.749282,1.471644e+11,3.491911e+22
5,DecisionTreeRegressor,new_deaths,1.215371e+05,3.486217e+02,0.713463,59.353628,4.965974e+09,4.092726e+19
6,DecisionTreeRegressor,total_cases,1.020669e+13,3.194791e+06,0.978488,586562.251161,2.800056e+01,6.390524e+01
7,DecisionTreeRegressor,total_deaths,1.568890e+10,1.252554e+05,0.916314,15489.576031,3.529388e+01,1.917392e+02